apiVersion: v2
name: go-app
description: A Helm chart for go app
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- condition: ingressController.enabled
  name: nginx-ingress-controller
  version: "11.1.0"
  repository: "https://charts.bitnami.com/bitnami"
- condition: redis.enabled
  name: redis
  version: "19.1.3"
  repository: "https://charts.bitnami.com/bitnami"