global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go_app'
    static_configs:
      - targets: ['go_app:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']