{
 "title": "4_Golden_Signals",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(indexHandler_request_count{job=\"app\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(rate(http_request_index_handler_duration_seconds_bucket{job=\"app\"}[1m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}