version: "3.9"

networks:
    local:

services:
    app:
        build:
            dockerfile: ./compose/Dockerfile
            args:
                - GOLANG_VERSION=1.22.3
            context: ../
        command: go run /opt/main.go
        ports:
            - "8080:8080"
        develop:
            watch:
                -   action: sync+restart
                    path: ../src/
                    target: /opt/
        environment:
            - REDIS_ADDR=redis:6379
        networks:
            - local

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/root/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_PASSWORD=my-password
            - REDIS_PORT=6379
            - REDIS_DATABASES=1
        networks:
            - local
