---
apiVersion: v1
kind: Namespace
metadata:
    name: somenamespace
    labels:
        name: somenamespace

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    namespace: somenamespace
    name: somenamespace-full
rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]

---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: somenamespace
    namespace: somenamespace
spec:
    hard:
        configmaps:             "100"
        limits.cpu:             "10"
        limits.memory:          "20Gi"
        persistentvolumeclaims: "3"
        pods:                   "100"
        replicationcontrollers: "0"
        requests.cpu:           "2"
        requests.memory:        "4Gi"
        requests.storage:       "50Gi"
        resourcequotas:         "1"
        secrets:                "100"
        services:               "100"
        services.loadbalancers: "0"
        services.nodeports:     "0"
